### ISSUE TITLE
v1.0.6 breaks API 1.0 authentication

### ISSUE THREAD

**Issue by db0** [cyberark/ansible-security-automation-collection#22]
## Summary
The latest collection seems to be breaking backwards compatibility with API 1.0 instances.

The following (copied from the official examples) doesn't work anymore in 1.0.6 but it works in 1.0.5
```
- name: Logon - Not use_shared_logon_authentication
  cyberark_authentication:
    api_base_url: "{{ web_services_base_url }}"
    username: "{{ password_object.password }}"
    password: "{{ password_object.passprops.username }}"
    use_shared_logon_authentication: no
```

## Steps to Reproduce
Using 1.0.6 Run the example authentication against API 1.0 SAM Vault server

## Expected Results
Authenticate and retrieve token in ansible_facts

## Actual Results (including error logs, if applicable)
```
fatal: [server]: FAILED! => {"changed": false, "headers": {"Content-Type": "application/json"}, "msg": "Error while performing authentication.Please validate parameters provided, and ability to logon to CyberArk.\n*** end_point=https://sam.example.com/PasswordVault/API/Auth/CyberArk/Logon\n ==> HTTP Error 403: Forbidden", "payload": "{\"username\": \"USERNAME\", \"password\": \"********\"}", "status_code": 403}
```

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
* Ansible v. 2.10
* collection v1.0.6

## Additional Information
It seems that the wrong URL is sent with 1.0.6. It is sending to `/PasswordVault/API/Auth/CyberArk/Logon` when it should be sending to `/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon`. I.e. it is not detecting which API version is being used.
