### ISSUE TITLE
cyberark_account module throws error for invalid api_base_url when pulled from registered session

### ISSUE THREAD

**Issue by jamesmarshall24** [cyberark/ansible-security-automation-collection#31]
## Summary

Attempting to use collection version 1.0.7 with cyberark_account after a successful cyberark_authentication results in an error with api_base_url

## Steps to Reproduce

1. Install latest collection: ansible-galaxy collection install cyberark.pas:1.0.7
2. Write a playbook with contents similar to the following:
```yaml
    - name: Logon to CyberArk Vault using PAS Web Services SDK
      cyberark.pas.cyberark_authentication:
        api_base_url: "http://components.cyberark.local"
        validate_certs: no
        username: "bizdev"
        password: "Cyberark1"

    - name: Creating an Account using the PAS WebServices SDK
      cyberark.pas.cyberark_account:
        logging_level: DEBUG
        identified_by: "address,username"
        safe: "Test"
        address: "cyberark.local"
        username: "administrator-x"
        platform_id: WinServerLocal
        secret: "@N&Ibl3!"
        platform_account_properties:
            LogonDomain: "cyberark"
            OwnerName: "ansible_user"
        secret_management:
            automatic_management_enabled: true
        state: present
        cyberark_session: "{{ cyberark_session }}"
      register: cyberarkaction
```
3. Run the playbook

## Expected Results

Account created

## Actual Results

Line: [cyberark_account.py#L1075](https://github.com/cyberark/ansible-security-automation-collection/blob/master/plugins/modules/cyberark_account.py#L1075) fails with invalid formatting

_Waiting for error trace_

## Reproducible

   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

1.0.7

## Environment setup

* RHEL8
* python3
