### ISSUE TITLE
Cannot delete ssh keys

### ISSUE THREAD

**Issue by Kanabos** [cyberark/ansible-security-automation-collection#43]
## Summary

SSH key cannot be delete using `cyberark.pas.cyberark_account` module, task fails.

## Steps to Reproduce

Use cyberark_account module to delete an ssh key from the Vault:

```yaml
- name: "Delete SSH key"
  cyberark.pas.cyberark_account:
    identified_by: "address,username,platform_id"
    username: "{{ user }}"
    address: "{{ address }}"
    safe: "{{ safe_name }}"
    platform_id: "{{ platform_id }}"
    secret_type: "key"
    state: absent
    cyberark_session: "{{ cyberark_session }}"
```

## Expected Results

- **Account is deleted** from Cyberark Vault
- Task succeed in ansible, http response code 200 from pvwa

## Actual Results

- **Account is not deleted** from Cyberark Vault
- Task fails in ansible, http response code 400, body contains:

```json
{
 "ErrorCode": "PASWS056E",
 "ErrorMessage": "The account is not valid for delete"
}
```

## Reproducible

   * [X] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

cyberark.pas collection version `1.0.13`

## Environment setup

- Privilege Access Manager `v12.2`
- Ansible Tower

## Additional Information

According to this answer on [Cyberark Technical Community](https://cyberark-customers.force.com/s/question/0D52J00006k8zrNSAQ/rest-delete-ssh-key-account-fails-pasws056e-the-account-is-not-valid-for-delete), v10 pvwa api isn't able to delete ssh keys.

Deletion works using v9 api and uri module. Here is my **workaround**:
```yaml
- name: "Get ssh key id"
  cyberark.pas.cyberark_account:
    identified_by: "address,username,platform_id"
    username: "{{ user }}"
    address: "{{ address }}"
    safe: "{{ safe_name }}"
    platform_id: "{{ platform_id }}"
    secret_type: "key"
    state: present
    cyberark_session: "{{ cyberark_session }}"
  register: getaction

- name: "Delete ssh key"
  uri:
    url: "https://{{ pvwa_url }}/PasswordVault/WebServices/PIMServices.svc/Accounts/{{ getaction.result.result.id }}"
    method: DELETE
    validate_certs: yes
    return_content: yes
    headers:
      Authorization: "{{ cyberark_session.token }}"
    status_code: 200
```
