### ISSUE TITLE
Add a `meta/extensions.yml` file for displaying EDA content in Automation Hub

### ISSUE THREAD

**Issue by alisonlhart** [cyberark/ansible-security-automation-collection#68]
To display EDA content on Ansible Automation Hub, there is an additional file needed in the collection.

Add the `meta/extensions.yml` file to the collection with the following contents:
```
extensions:
  - args:
      ext_dir: eda/plugins/event_filter
  - args:
      ext_dir: eda/plugins/event_source
```
This will cause the EDA plugin to display under the collection's "Contents" tab in Automation Hub. 

See the [ansible.eda collection source](https://github.com/ansible/event-driven-ansible/blob/main/meta/extensions.yml) for reference. 

(Note: Depends on #67 to work properly)
